version: '2'
services:
  es_standalone:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.0.0-rc2-SNAPSHOT
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "node.master=true"
      - "node.data=true"
      - xpack.security.enabled=true
      - xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/certificates/elasticsearch1/elasticsearch1.key
      - xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/certificates/elasticsearch1/elasticsearch1.crt 
      - xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/certificates/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.http.ssl.enabled=true
    networks:
      app-tls:
      internal-tls:
        ipv4_address: 172.18.10.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - ./data/es_s1:/usr/share/elasticsearch/data
      - ./certificates:/usr/share/elasticsearch/config/x-pack/certificates
    ports:
      - 9200:9200

networks: 
  app-tls:
    driver: bridge
  internal-tls:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.10.0/24
        gateway: 172.18.10.1
