##FROM rgoyard/apache-proxy:latest
## pinning to specific version of this dependency so I don't break things in the future
FROM rgoyard/apache-proxy@sha256:662c366792ac58d330432a3a704226467c151e4edf387c62ca4ac16c7cec6f0b
MAINTAINER Dave Erickson <david.erickson@gmail.com>
ADD proxy.conf /conf/